version: '3.7'

services:
    risos:
        image: risos
        container_name: risos
        command: >
            sh -c "gunicorn risos.wsgi:application --bind 0.0.0.0:8000"
        ports:
            - "8000:8000"
        environment:
            - REDIS_HOST=redis
        depends_on:
            - redis
        volumes:
            - static_volume:/home/app/web/staticfiles
            - .:/home/app/web/
    redis:
        image: redis:latest
        ports:
            - "6379:6379"


    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env.prod.db
        ports:
            - "5432:5432"
        

    celery:
        restart: always
        image: risos
        command: celery -A risos worker --loglevel=debug --concurrency=8
        volumes:
            - .:/home/app/web
        depends_on:
            - redis
            - risos

    ai:
        image: ai
        container_name: ai
        command: uvicorn main:app --host 0.0.0.0 --port 4557 --reload --debug --workers 3
        volumes:
            - ./ai:/app
        depends_on:
            - risos
            - celery
        ports:
            - "4557:4557"

    nginx:
        image: risos_nginx
        container_name: nginx
        restart: always
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - static_volume:/home/app/web/staticfiles
        ports:
            - 80:80
            - 443:443
        depends_on:
            - risos


volumes:
    static_volume:
    postgres_data: