version: '3.7'

services: 
    risos:
        image: risos
        command: > 
            sh -c "python manage.py makemigrations && python -u manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        environment: 
            - REDIS_HOST=redis
        depends_on: 
            - redis
        volumes: 
            - static_volume:/home/app/web/staticfiles
            - .:/home/app/web
            - ./data/db.sqlite3:/home/app/web/data/db.sqlite3
    
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
    
    celery:
        restart: always
        image: risos
        command: celery -A risos worker --loglevel=debug --concurrency=8
        volumes: 
            - .:/home/app/web
        depends_on: 
            - redis
            - risos
        


volumes: 
    static_volume:
    