version: '3.7'

services: 
    risos:
        build: 
            context: .
        command: > 
            sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        environment: 
            - RESIS_HOST=redis
        depends_on: 
            - redis
        volumes: 
            - static_volume:/home/app/web/staticfiles
            - .:/home/web/app
    
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
    
    celery:
        restart: always
        build:
            context: .
        command: celery -A risos worker --loglevel=debug --concurrency=8
        volumes: 
            - .:/home/web/app
        depends_on: 
            - redis
            - risos
        


volumes: 
    static_volume:
    