# Generated by Django 3.1.7 on 2021-12-01 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extendProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('invoice', 'INVOICE'), ('order', 'ORDER')], max_length=50)),
                ('object_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NotifReceiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extendProfile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('message', models.CharField(max_length=250)),
                ('status', models.CharField(blank=True, choices=[('failed', 'FAILED'), ('success', 'SUCCESS')], max_length=10, null=True)),
                ('report_url', models.CharField(blank=True, max_length=250, null=True)),
                ('notif_id', models.CharField(blank=True, max_length=50, null=True)),
                ('notif_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notification.notifservice')),
                ('receivers', models.ManyToManyField(related_name='notifications', to='notification.NotifReceiver')),
            ],
        ),
    ]
