# Generated by Django 3.1.7 on 2021-08-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20210822_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(blank=True, choices=[('failed', 'FAILED'), ('success', 'SUCCESS')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='notifservice',
            name='object_type',
            field=models.CharField(choices=[('invoice', 'INVOICE'), ('order', 'ORDER')], max_length=50),
        ),
    ]
