# Generated by Django 3.1.7 on 2021-06-21 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extendProfile', '0002_auto_20210619_1302'),
        ('notification', '0011_auto_20210620_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiver',
            name='user',
        ),
        migrations.AddField(
            model_name='receiver',
            name='Profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extendProfile.profile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='service',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(blank=True, choices=[('failed', 'FAILED'), ('success', 'SUCCESS')], max_length=10, null=True),
        ),
    ]
