# Generated by Django 3.1.7 on 2021-06-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0012_auto_20210621_0714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiver',
            old_name='Profile',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(blank=True, choices=[('success', 'SUCCESS'), ('failed', 'FAILED')], max_length=10, null=True),
        ),
    ]
