# Generated by Django 3.1.7 on 2021-06-21 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0013_auto_20210621_0715'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notification',
        ),
    ]
