# Generated by Django 3.1.7 on 2021-06-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0013_auto_20210619_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(blank=True, choices=[('failed', 'FAILED'), ('success', 'SUCCESS')], max_length=10, null=True),
        ),
    ]
