# Generated by Django 3.1.7 on 2021-06-21 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0014_delete_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receiver',
        ),
    ]
