# Generated by Django 3.1.7 on 2021-06-21 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extendProfile', '0002_auto_20210619_1302'),
        ('notification', '0016_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extendProfile.profile'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('message', models.CharField(max_length=250)),
                ('service', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('failed', 'FAILED'), ('success', 'SUCCESS')], max_length=10, null=True)),
                ('report_url', models.CharField(blank=True, max_length=250, null=True)),
                ('notif_id', models.CharField(blank=True, max_length=50, null=True)),
                ('receivers', models.ManyToManyField(related_name='notifications', to='notification.Receiver')),
            ],
        ),
    ]
