# Generated by Django 3.1.7 on 2021-06-22 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notification', '0017_auto_20210621_0750'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='NotifService',
        ),
    ]
