# Generated by Django 3.1.7 on 2021-06-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0018_auto_20210622_1024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
