# Generated by Django 3.1.7 on 2021-06-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extendProfile', '0002_auto_20210619_1302'),
        ('notification', '0020_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='receivers',
            field=models.ManyToManyField(related_name='notifications', to='extendProfile.Profile'),
        ),
        migrations.DeleteModel(
            name='Receiver',
        ),
    ]
