# Generated by Django 3.1.7 on 2021-06-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0022_auto_20210622_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='receivers',
            field=models.ManyToManyField(related_name='notifications', to='notification.NotifReceiver'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(blank=True, choices=[('failed', 'FAILED'), ('success', 'SUCCESS')], max_length=10, null=True),
        ),
    ]
