# Generated by Django 3.1.7 on 2021-06-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0026_auto_20210622_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='service',
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(blank=True, choices=[('success', 'SUCCESS'), ('failed', 'FAILED')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='NotifService',
        ),
    ]
