# Generated by Django 3.1.7 on 2021-06-22 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0027_auto_20210622_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(choices=[('order completed', 'Order Completed'), ('order updated', 'Order Updated')], max_length=250),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(blank=True, choices=[('failed', 'FAILED'), ('success', 'SUCCESS')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notification.notifservice'),
        ),
    ]
