# Generated by Django 3.1.7 on 2021-06-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0029_auto_20210623_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifservice',
            name='object_type',
            field=models.CharField(choices=[('order', 'ORDER'), ('invoice', 'INVOICE')], max_length=50),
        ),
    ]
