# Generated by Django 3.1.7 on 2021-07-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0039_auto_20210722_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(choices=[('order updated', 'Order Updated'), ('order completed', 'Order Completed')], max_length=250),
        ),
    ]
