# Generated by Django 3.1.7 on 2021-07-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0040_auto_20210722_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(choices=[('order completed', 'Order Completed'), ('order updated', 'Order Updated')], max_length=250),
        ),
    ]
