# Generated by Django 3.1.7 on 2021-07-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0041_auto_20210722_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifservice',
            name='object_type',
            field=models.CharField(choices=[('invoice', 'INVOICE'), ('order', 'ORDER')], max_length=50),
        ),
    ]
