# Generated by Django 3.1.7 on 2021-08-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0055_auto_20210804_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifservice',
            name='object_type',
            field=models.CharField(choices=[('invoice', 'INVOICE'), ('order', 'ORDER')], max_length=50),
        ),
    ]
