# Generated by Django 3.1.7 on 2021-02-22 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('lab', 'Lab')], default='doctor', max_length=120)),
                ('full_name', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive'), ('freetrial', 'Freetrial'), ('banned', 'Banned')], default='freetrial', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(blank=True, max_length=40, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
