# Generated by Django 3.1.7 on 2021-06-17 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extendProfile', '0007_auto_20210610_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OTP', to='extendProfile.profile'),
        ),
    ]
