# Generated by Django 3.1.7 on 2021-05-18 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smileDesign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smiledesignservice',
            name='related_smile_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smileDesign.smiletype'),
        ),
    ]
