# Generated by Django 3.1.7 on 2021-06-19 08:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smileDesign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RectAngle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.FloatField()),
                ('y1', models.FloatField()),
                ('x2', models.FloatField()),
                ('y2', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='smiledesignservice',
            name='related_smile_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smileDesign.smiletype'),
        ),
        migrations.CreateModel(
            name='SmilePlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('unit', models.CharField(choices=[('px', 'Pixel'), ('cm', 'Centi Meter')], default='px', max_length=50)),
                ('related_smile_design', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smile_plot', to='smileDesign.smiledesignservice')),
            ],
        ),
        migrations.CreateModel(
            name='OutRectangle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('rect_angle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smileDesign.rectangle')),
                ('related_smile_plot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='out_rectangle', to='smileDesign.smileplot')),
            ],
        ),
        migrations.CreateModel(
            name='TeethCoordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('teeth_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('rect_angle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smileDesign.rectangle')),
                ('related_smile_plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teeth_cordinates', to='smileDesign.outrectangle')),
            ],
            options={
                'unique_together': {('teeth_number', 'related_smile_plot')},
            },
        ),
    ]
