# Generated by Django 3.1.7 on 2021-06-19 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smileDesign', '0002_auto_20210619_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smileplot',
            name='related_smile_design',
        ),
        migrations.AlterUniqueTogether(
            name='teethcoordinate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teethcoordinate',
            name='rect_angle',
        ),
        migrations.RemoveField(
            model_name='teethcoordinate',
            name='related_smile_plot',
        ),
        migrations.DeleteModel(
            name='OutRectangle',
        ),
        migrations.DeleteModel(
            name='SmilePlot',
        ),
        migrations.DeleteModel(
            name='TeethCoordinate',
        ),
    ]
