# Generated by Django 3.1.7 on 2021-06-19 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smileDesign', '0006_smileplot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmilePlot',
        ),
    ]
