# Generated by Django 3.1.7 on 2021-06-19 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smileDesign', '0009_auto_20210619_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smileplot',
            name='related_smile_design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smile_plot', to='smileDesign.smiledesignservice'),
        ),
    ]
