# Generated by Django 3.1.7 on 2021-06-19 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smileDesign', '0015_auto_20210619_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smileplot',
            name='unit',
            field=models.CharField(choices=[('px', 'Pixel'), ('cm', 'Centi Meter')], default='px', max_length=50),
        ),
        migrations.AlterField(
            model_name='teethcoordinate',
            name='related_smile_plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teeth_cordinates', to='smileDesign.smileplot'),
        ),
    ]
