# Generated by Django 3.1.7 on 2021-07-05 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smileDesign', '0027_auto_20210701_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='teeth',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Tooth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('tooth_image', models.ImageField(blank=True, null=True, upload_to='Teeth/')),
                ('related_teeth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smileDesign.teeth')),
            ],
        ),
    ]
