# Generated by Django 3.1.7 on 2021-07-15 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smileDesign', '0028_auto_20210705_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smileplot',
            name='unit',
            field=models.CharField(choices=[('cm', 'Centi Meter'), ('px', 'Pixel')], default='px', max_length=50),
        ),
        migrations.AlterField(
            model_name='tooth',
            name='related_teeth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tooths', to='smileDesign.teeth'),
        ),
    ]
