# Generated by Django 3.1.7 on 2021-07-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smileDesign', '0030_auto_20210722_0729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smiledesignservice',
            old_name='full_smile_image',
            new_name='smile_image_result',
        ),
        migrations.RemoveField(
            model_name='smiledesignservice',
            name='optional_image',
        ),
        migrations.RemoveField(
            model_name='smiledesignservice',
            name='side_image',
        ),
        migrations.RemoveField(
            model_name='smiledesignservice',
            name='smile_image',
        ),
        migrations.AlterField(
            model_name='smileplot',
            name='unit',
            field=models.CharField(choices=[('cm', 'Centi Meter'), ('px', 'Pixel')], default='px', max_length=50),
        ),
    ]
