# Generated by Django 3.1.7 on 2021-07-22 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smileDesign', '0032_auto_20210722_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smiledesignservice',
            name='related_smile_type',
        ),
        migrations.AddField(
            model_name='smiledesignservice',
            name='related_smile_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smileDesign.smilecategory'),
        ),
        migrations.AddField(
            model_name='smiledesignservice',
            name='related_smile_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smileDesign.smilecolor'),
        ),
        migrations.DeleteModel(
            name='SmileType',
        ),
    ]
