# Generated by Django 3.1.7 on 2021-07-24 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businessLogic', '0062_auto_20210724_1942'),
        ('smileDesign', '0036_auto_20210724_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smiledesignservice',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smile_designs', to='businessLogic.patient'),
        ),
        migrations.AlterField(
            model_name='smileplot',
            name='unit',
            field=models.CharField(choices=[('px', 'Pixel'), ('cm', 'Centi Meter')], default='px', max_length=50),
        ),
    ]
