# Generated by Django 3.1.7 on 2021-07-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smileDesign', '0037_auto_20210724_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smileplot',
            name='related_smile_design',
        ),
        migrations.AlterUniqueTogether(
            name='teethcoordinate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teethcoordinate',
            name='rect_angle',
        ),
        migrations.RemoveField(
            model_name='teethcoordinate',
            name='related_smile_plot',
        ),
        migrations.AddField(
            model_name='smiledesignservice',
            name='status',
            field=models.CharField(choices=[('ready', 'READY'), ('notready', 'NOTREADY')], default='notready', max_length=20),
        ),
        migrations.DeleteModel(
            name='OutRectangle',
        ),
        migrations.DeleteModel(
            name='RectAngle',
        ),
        migrations.DeleteModel(
            name='SmilePlot',
        ),
        migrations.DeleteModel(
            name='TeethCoordinate',
        ),
    ]
