# Generated by Django 3.1.7 on 2021-07-25 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smileDesign', '0038_auto_20210724_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smiledesignservice',
            name='patient',
        ),
    ]
