# Generated by Django 3.1.7 on 2021-07-27 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businessLogic', '0070_auto_20210727_0904'),
        ('smileDesign', '0043_auto_20210726_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='smiledesignservice',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smile_designs', to='businessLogic.doctor'),
        ),
        migrations.AddField(
            model_name='smiledesignservice',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smile_designs', to='businessLogic.patient'),
        ),
        migrations.AlterField(
            model_name='smileplot',
            name='unit',
            field=models.CharField(choices=[('cm', 'Centi Meter'), ('px', 'Pixel')], default='px', max_length=50),
        ),
    ]
