# Generated by Django 3.1.7 on 2021-07-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smileDesign', '0044_auto_20210727_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='smiledesignservice',
            name='central_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
