# Generated by Django 3.1.7 on 2021-02-22 13:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smileDesign', '0001_initial'),
        ('extendProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('related_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='extendProfile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='businessLogic.servicecategory')),
                ('related_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessLogic.doctor')),
                ('related_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessLogic.patient')),
                ('related_smile_design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smileDesign.smiledesignservice')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ManyToManyField(through='businessLogic.Service', to='businessLogic.Doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='related_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='extendProfile.profile'),
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('related_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='extendProfile.profile')),
            ],
        ),
    ]
