# Generated by Django 3.1.7 on 2021-12-01 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extendProfile', '0001_initial'),
        ('smileDesign', '0001_initial'),
        ('businessLogic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='related_smile_design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smileDesign.smiledesignservice'),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ManyToManyField(to='businessLogic.Doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_pic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='businessLogic.patientpic'),
        ),
        migrations.AddField(
            model_name='patient',
            name='related_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='extendProfile.profile'),
        ),
        migrations.AddField(
            model_name='order',
            name='finalized_lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='businessLogic.lab'),
        ),
        migrations.AddField(
            model_name='order',
            name='related_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='businessLogic.service'),
        ),
        migrations.AddField(
            model_name='log',
            name='related_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='businessLogic.order'),
        ),
        migrations.AddField(
            model_name='labpic',
            name='lab',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='labPics', to='businessLogic.lab'),
        ),
        migrations.AddField(
            model_name='lab',
            name='related_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='extendProfile.profile'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='related_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='businessLogic.order'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='related_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='extendProfile.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='labpic',
            unique_together={('lab', 'number')},
        ),
    ]
