# Generated by Django 3.1.7 on 2021-08-22 08:43

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businessLogic', '0002_auto_20210822_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='actual_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='expected_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='related_lab',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='related_service',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
        migrations.AlterField(
            model_name='order',
            name='actual_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 20, 8, 43, 39, 703427), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 21, 8, 43, 39, 703378), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('invoice ready', 'Invoice Ready'), ('accept', 'Accept'), ('reject', 'Reject'), ('reject and resend', 'Reject And Resend'), ('molding', 'Molding'), ('ditch', 'Ditch'), ('scan', 'Scan'), ('water wax', 'Water Wax'), ('designing', 'Designing'), ('print/milling', 'Print/Milling'), ('ceramic', 'Ceramic')], default='sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='tooth',
            name='tooth_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(11), django.core.validators.MaxValueValidator(48)]),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('status', models.CharField(max_length=50)),
                ('related_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='businessLogic.order')),
            ],
        ),
    ]
