# Generated by Django 3.1.7 on 2021-02-22 14:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businessLogic', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='rating',
            field=models.FloatField(default=5.1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='actual_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='expected_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='finalized_lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='businessLogic.lab'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('delayed', 'Delayed'), ('sent', 'Sent'), ('underdevelopment', 'Under Development'), ('finalized', 'Finalized'), ('cancelled', 'Cancelled')], default='processing', max_length=20),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('expected_date', models.DateTimeField(blank=True, null=True)),
                ('actual_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('finalized', 'Finalized'), ('cancelled', 'Cancelled')], default='processing', max_length=20)),
                ('reciept_image', models.ImageField(upload_to='')),
                ('related_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessLogic.lab')),
                ('related_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessLogic.order')),
                ('related_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessLogic.service')),
            ],
        ),
    ]
