# Generated by Django 3.1.7 on 2021-08-22 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessLogic', '0003_auto_20210822_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='message',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='actual_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 20, 12, 42, 45, 941656), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 21, 12, 42, 45, 941593), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('invoice ready', 'Invoice Ready'), ('accept', 'Accept'), ('reject', 'Reject'), ('reject and resend', 'Reject And Resend'), ('molding', 'Molding'), ('ditch', 'Ditch'), ('scan', 'Scan'), ('water wax', 'Water Wax'), ('designing', 'Designing'), ('print/milling', 'Print/Milling'), ('ceramic', 'Ceramic'), ('ready', 'ready')], default='sent', max_length=20),
        ),
    ]
