# Generated by Django 3.1.7 on 2021-05-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessLogic', '0004_auto_20210513_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pic1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='pic2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='pic3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='pic4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
