# Generated by Django 3.1.7 on 2021-05-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessLogic', '0005_auto_20210515_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pic1',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pic2',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pic3',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pic4',
        ),
    ]
