# Generated by Django 3.1.7 on 2021-08-22 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessLogic', '0009_auto_20210822_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='actual_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 20, 13, 25, 31, 769694), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 21, 13, 25, 31, 769648), null=True),
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
