# Generated by Django 3.1.7 on 2021-08-22 13:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extendProfile', '0001_initial'),
        ('businessLogic', '0012_auto_20210822_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='actual_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 20, 13, 26, 56, 92468), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 21, 13, 26, 56, 92421), null=True),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('doctor', 'Doctor'), ('lab', 'Lab')], max_length=50)),
                ('receiver_type', models.CharField(choices=[('doctor', 'Doctor'), ('lab', 'Lab')], max_length=50)),
                ('message', models.CharField(max_length=50)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='extendProfile.profile')),
                ('related_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessLogic.order')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='extendProfile.profile')),
            ],
        ),
    ]
