# Generated by Django 3.1.7 on 2021-08-22 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessLogic', '0013_auto_20210822_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='receiver_type',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sender_type',
        ),
        migrations.AddField(
            model_name='ticket',
            name='messgae_status',
            field=models.CharField(blank=True, choices=[('read', 'Read'), ('unread', 'Unread')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='actual_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 20, 13, 34, 10, 874798), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 21, 13, 34, 10, 874752), null=True),
        ),
    ]
