# Generated by Django 3.1.7 on 2021-05-26 09:47

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businessLogic', '0015_auto_20210522_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='rating',
            field=models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='lab',
            name='rating',
            field=models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='actual_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 24, 9, 47, 35, 1079), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 25, 9, 47, 35, 1034), null=True),
        ),
        migrations.CreateModel(
            name='LabPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='labpics/')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='labpics/')),
                ('pic3', models.ImageField(blank=True, null=True, upload_to='labpics/')),
                ('pic4', models.ImageField(blank=True, null=True, upload_to='labpics/')),
                ('pic5', models.ImageField(blank=True, null=True, upload_to='labpics/')),
                ('pic6', models.ImageField(blank=True, null=True, upload_to='labpics/')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labPics', to='businessLogic.lab')),
            ],
        ),
    ]
