# Generated by Django 3.1.7 on 2021-06-05 10:39

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businessLogic', '0016_auto_20210526_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadColorReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ToothSevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='labpic',
            old_name='pic1',
            new_name='pic',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='name',
        ),
        migrations.RemoveField(
            model_name='labpic',
            name='pic2',
        ),
        migrations.RemoveField(
            model_name='labpic',
            name='pic3',
        ),
        migrations.RemoveField(
            model_name='labpic',
            name='pic4',
        ),
        migrations.RemoveField(
            model_name='labpic',
            name='pic5',
        ),
        migrations.RemoveField(
            model_name='labpic',
            name='pic6',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.RemoveField(
            model_name='patientpic',
            name='patient',
        ),
        migrations.AddField(
            model_name='labpic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='labpic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_pic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='businessLogic.patientpic'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='related_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='businessLogic.order'),
        ),
        migrations.AlterField(
            model_name='labpic',
            name='lab',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='labPics', to='businessLogic.lab'),
        ),
        migrations.AlterField(
            model_name='order',
            name='actual_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 3, 10, 39, 19, 768440), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 4, 10, 39, 19, 768390), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='related_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='businessLogic.service'),
        ),
        migrations.AlterField(
            model_name='patientpic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='patientpic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='service',
            name='related_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='businessLogic.doctor'),
        ),
        migrations.CreateModel(
            name='Tooth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('tooth_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(48)])),
                ('is_bad_color', models.BooleanField(default=False)),
                ('bad_color_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='businessLogic.badcolorreason')),
                ('related_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Teeth', to='businessLogic.service')),
                ('tooth_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='businessLogic.toothsevice')),
            ],
        ),
    ]
