# Generated by Django 3.1.7 on 2021-06-01 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessLogic', '0017_auto_20210601_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.AlterField(
            model_name='order',
            name='actual_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 30, 12, 35, 24, 697891), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 31, 12, 35, 24, 697811), null=True),
        ),
    ]
