# Generated by Django 3.1.7 on 2021-06-06 07:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessLogic', '0018_auto_20210605_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='labpic',
            name='number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='badcolorreason',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='actual_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 4, 7, 46, 14, 420079), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 5, 7, 46, 14, 419995), null=True),
        ),
        migrations.AlterField(
            model_name='toothsevice',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='labpic',
            unique_together={('lab', 'number')},
        ),
    ]
