# Generated by Django 3.1.7 on 2021-07-24 14:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businessLogic', '0059_auto_20210722_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='actual_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 22, 14, 14, 46, 678871), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 22, 14, 14, 46, 678822), null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_pic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='businessLogic.patientpic'),
        ),
    ]
