# Generated by Django 3.1.7 on 2021-07-27 12:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businessLogic', '0071_auto_20210727_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_pic',
        ),
        migrations.AddField(
            model_name='patientpic',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_pic', to='businessLogic.patient'),
        ),
        migrations.AlterField(
            model_name='order',
            name='actual_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 25, 12, 54, 6, 897365), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 25, 12, 54, 6, 897320), null=True),
        ),
    ]
