# Generated by Django 3.1.7 on 2021-08-08 10:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessLogic', '0076_auto_20210804_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='rate_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lab',
            name='rate_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='lab',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='actual_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 6, 10, 48, 13, 349092), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 7, 10, 48, 13, 349019), null=True),
        ),
    ]
